### ISSUE TITLE
Obtain CREST Approved Penetration Testing Certification

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#102]
##  Summary

As the NHS, I want Tomo to be CREST Accredited for Penetration Testing, so I can assured they implement adequate data security throughout their systems

**Requirement of DAQ Section 6**

##  Other links or relevant information
- Has a Code-Level Security Assessment been undertaken by a CREST or other similar appropriate body
- Please provide evidence of certificate / report
- Has the Code-Level Security Assessment been undertaken by an external body
- What OWASP Level has the Code-Level Security Assessment been undertaken
- Has the Code-Level Security Assessment been undertaken against the correct standard and level for the application (see questions for OWASP definition below)
- Does the App access, process or store Personal and/or Sensitive Data?
- Is sensitive data persisted to the mobile device?
- Does the App access, process or store Personal and/or Sensitive Data?

##  Acceptance Criteria

- [x] @eddieTomo to find out cost and requirements of Certification
- [x] Discuss requirements with Paolo, GP and Dev
- [x] Determine work required to meet CREST Certification
- [x] Write issues and implement required development changes
- [x] Submit to accrediting body for certification
- [ ] If necessary, implement any remedial action required by accrediting company.

##  Definition of Done

- [x] Tomo is CREST Certified for Penetration Testing
- [x] Certificate included in Supporting Docs folder

**Comment by eddieTomo** [comment]
As of 12/11/2019 we have gone through Penetration Testing and a Code Level Security Assesssment by XYOne.

The following issues were noted:

#### PenTest
1. Weak Cipher Encryption Protocols (MED) - GP has partially fixed this already, remainder of of the fixes would require us to change to a paid plan with Auth0 (plan would in fact be a downgrade compared to current allowances)
2.  Host Header Poisoning (MED) - GP has fixed this.
3. HTTP Security Headers Not Set (LOW)

#### CLSA
1. Use of a broken/risky encryption algorithm (MED)
2. Not validating user supplied input resulting in potential directory traversal flaw (MED)
3. Improper Resource Shutdown or Release (LOW)

NHS Digital only require immediate fixes for CRITICAL and HIGH level risks, however Saga have stated they require immediate fixes for MEDIUM level risks as well.

@GusBC is confirming with Saga whether we need to fully fix the Weak Cipher Encryption Protocol risk
@eddieTomo is confirming with XYOne when we need to have implemented the fixes in order to claim the retest included as part of the fees (either 10/12/19 or 21/01/20 TBC)
@remihellotomo to schedule work for MEDIUM issues once current Saga tickets on `Tomo` are completed

**Comment by eddieTomo** [comment]
This has been completed.  A summary of issues found and fixes implemented is available at https://docs.google.com/spreadsheets/d/1bEy2JMVPrmu_G-O0xFLl21jRDVzV-X6hrA_fS1Jmhbo/edit?usp=sharing
