### ISSUE TITLE
Identify Example Activity/Habit clearly for exclusion from LSBU2 data

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#115]
## User Story
As a researcher, I want to exclude the Example Activity (or Habit if made into one) from my analysis, so that I only study individual user habit choices, not ones made by Tomo

## Acceptance Criteria
- [x] Mark if a user completes onboarding example activity
- [x] Mark if a user turns the onboarding example activity into a habit in a unique way 
- [ ] Set `is_habit` on onboarding example habit (if made into one).

## Definition of Done
- [x] Can if/when a user completes the onboarding example activity 
- [x] Can see if/when a user turns the onboarding example activity into a habit
- [x] Can search for all activites/habits/photo uploads that are not the example activity.

**Comment by eddieTomo** [comment]
This is now being tracked using the `context.feature: example_activity` and `context.feature: habit_example` parameters that will be deployed with version 5 dialogues
