### ISSUE TITLE
Logstash configuration changes

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#116]
##  Summary

Summary of issue or user story if appropriate:
As an analyst I want to amend the configuration file for logstash so I can enrich log data as required before indexing into elasticsearch or storage in s3

N.B. This issue is a running ticket of code changes i need to make for various other issues

##  Acceptance Criteria

- [x] Get current `logstash.conf` from GP
- [x] Parse json nested arrays within logs
  - this is caused by `context.info` fields being presented as a literal string, need to find out why this is
- [X] Add filter to fix sender/user field mismatch on help others actions
- [x] Convert booleans to strings to avoid elasticsearch bugs
  - Need to gather list of boolean fields
- [x] Anonymize last octet of ip address to protect user data
- [x] Add filters & ruby code to time how long it takes for a photo to be checked
- [x] Enrich purchase logs with additional information
- [x] Add ruby code to calculate week number of user
  - also added code to calculate day number
- [x] Add ruby code to calculate day questionnaire taken
- [X] Tag LSBU2 logs for output filtering
- [ ] On production only send LSBU2 messages to s3
- [ ] On dev, send all messages to s3
- [X] Add ids to all functions for easy performance monitoring during testing

Logstash Ruby reference is at https://www.elastic.co/guide/en/logstash/current/plugins-filters-ruby.html

##  Definition of Done

- N.B. some changes require new field data such as `firstlogin_ts` to be logged to function, but `if` filters have been used to avoid throwing errors when these are missing

- [x] All changes tested locally @eddieTomo 
  - [x] Test nested array parsing
    - [x] Fix context.info literal strings
  - [X] Test sender/user remap
  - [x] Test boolean fields converting to strings
  - [x] Test ip anonymization
  - [X] Test photo check elapsed filter
  - [X] Test purchase adding additional fields
  - [X] Test day and week cohort calculators 
  - [X] Test question day calculator for all scenarios (-1, 0, +1, out of bounds, not present)
 - [X] Test LSBU2 tagged output filter fuctionality

- [x] Test with streamed in ndjson data from dev using full local ELK stack
- [x] Review performance logs

Dev
- [x] Changes to logstash configuration added by GP
- [x] Changes tested by GP
  - @eddie to provide test input and expected output
- [x] Changes implemented on `dev` EC2 server.
- [x] Log data correctly enriched in elasticsearch and available in s3 outputs for `tomo-dev` index
- [x] Monitoring shows no excessive resource increase on EC2

Prod
- [x] Changes pushed to `prod` EC2 server
- [x] Log data correctly enriched in elasticsearch and available in s3 outputs for `tomo-prod` index
- [x] Monitoring shows no excessive resource increase on EC2

Documentation
- [x] Updated Logstash section on [ELK Stack & Index Management 2019](https://github.com/ActivateMedia/tomo/wiki/ELK-Stack-&-Index-Management-2019)

**Comment by eddieTomo** [comment]
Calculating Week Numbers:

Date math must be executed using ruby code and use floor to round down to current week number

```ruby
filter {
     ruby {
            code => 'event.set("week_no", ((event.get("@timestamp") - event.get("firstlogin_ts")) / 604000).floor rescue 9999'
      }
    }
```

`rescue 9999` is used instead of `rescue nil` as rescue nil is computationally poor.

**Comment by eddieTomo** [comment]
## Calculate Day of Questionnaire

https://app.zenhub.com/workspaces/tomo-office-5b7d2321930be216d9f233ad/issues/remihellotomo/tomo-office/114

May need to adjust `event.set(QDay....)` in script below - look up how to set named k/v events in Ruby logstash plugin


```ruby
if [reference_ts] && [ts] in fields
  filter {
    ruby {
      code =>
        if 
          (
            ( event.get("ts") - event.get("reference_ts") ) / 86400 ) % 7 ) >= 1) && 
            ( event.get("ts") - event.get("reference_ts") ) / 86400 ) % 7 ) =< 2 )
          ) 
        { event.set("Q_day: 'D-1'")}
        else if  
          (
            ( event.get("ts") - event.get("reference_ts") ) / 86400 ) % 7 ) >= 0 ) && 
            ( event.get("ts") - event.get("reference_ts") ) / 86400 ) % 7 ) =< 1 )
          ) 
        { event.set("Q_day: 'D=0'")}
        else if  
          (
            ( event.get("ts") - event.get("reference_ts") ) / 86400 ) % 7 ) >= 6 ) && 
            ( event.get("ts") - event.get("reference_ts") ) / 86400 ) % 7 ) =< 7 )
          ) 
        { event.set("Q_day: 'D+1'")}
    }
  }
```

**Comment by eddieTomo** [comment]
## Add More Info to Purchase Tx

- Will need to properly parse context.info fields before this will be possible

```
if [productIdentifier] == "coursepackage" {
  mutate {
    id => coursepackage_price_info
    add_field => {
      "payment_amt" => "23.99"
      "income_amt" => "13.99"
    }
  }
}

if [productIdentifier] == "courseaddon" {
  mutate {
    id => courseaddon_price_info
    add_field => {
      "payment_amt" => "14.99"
      "income_amt" => "8.74"
    }
  }
}

if [productIdentifier] == "monthly" {
  mutate {
    id => monthly_price_info
    add_field => {
      "payment_amt" => "9.99"
      "income_amt" => "5.83"
    }
  }
}

if [transactionDate] {
  ruby {
    id => transactionDate_mapper
    code => 'event.set("purchase_day_no", ((event.get("transactionDate") - event.get("firstlogin_ts")) / 86400).floor rescue 999999'
  }
}
```

**Comment by eddieTomo** [comment]
currently live on dev outputting to both `tomo-dev` and `tomo-test` indexes.  monitoring for a few days before considering for production

**Comment by eddieTomo** [comment]
This has either been completed on production, or is awaiting work that has yet to be scheduled but has had separate tickets created for it.  Closing issue for now
