### ISSUE TITLE
4.0 Focus Group Usability Testing

### ISSUE THREAD

**Issue by remihellotomo** [remihellotomo/Tomo-Office#16]
As a product manager, I want to collect the team's intentions from the 4.0 Market User Testing, so that I can better identify the scope and plan for the implementation (around discussions and question)

Specifically, the immediate focus is to collect user feedback of the product from 3.10-4.0.  Where possible, can we ask questions around our product proposition for 4.0-4.1, such as target, segmentation, courses, etc. Where possible, this will be ancillary and should not interfere with the main objective of 3.10 to 4.0.

Steps to take
- [x] @eddieTomo to use the acceptance criteria of 4.0 Roadmap Epics in Zenhub as a starting point for collection and will pass around office for feedback
- [ ] @remihellotomo to review this and begin considering research plan doc and scoping procedure
- [ ] @remihellotomo and @fbalsaud to discuss with Activate all UX and UI and function questions we'd like to ask around 3.10 to 4.0 and what has been achieved with regard to product and user experience.
- [ ] @remihellotomo and @eddieTomo to scoping around time, budget, and performance/quality
- [ ] @remihellotomo and @fbalsaud to draft a discussion guide 
- [ ] @remihellotomo and @fbalsaud to get feedback from Activate on discussion guide
- [ ] @remihellotomo @fbalsaud to work with Activate on capture and consent forms
