### ISSUE TITLE
Buy courses from within app

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#53]
##  Summary

As a user I would like to be able to buy a course from within the app so that it is easy for me to buy or upgrade Tomo products

##  Acceptance Criteria

- [x] Add course pricing products into App Store Connect
- [x] Add ability to buy monthly and Ready/Set/Go packages within the app under the 'Subscription' page.
- [x] Upgrade from monthly subscription to course should start immediately
- [x] Upgrade from monthly subscription to course should start the user on the course mailchimp workflow
- [x] Upgrade from one course package to another should modify their subscription end date to the upgraded course package length
- [x] Cancelling subscriptions does not result in a refund, and the subscription only runs out at the end of the current subscription period

##  Definition of Done

Tested on dev
- [x] course offerings added in app store connect.
- [x] can buy subscription within app, can upgrade within app.
- [x] price is displayed correct in app
- [x] duration is displayed correct in app
- [x] duration is displayed correct on tomo-web
- [x] courses purchased via stripe push right duration to auth0 & mailchimp

Live on prod
- [x] can buy subscription within app, can upgrade within app.
- [x] price is displayed correct in app
- [x] duration is displayed correct in app
- [x] duration is displayed correct on tomo-web

##### 📅 Release Deadline:

**Comment by remihellotomo** [comment]
In progress as of 12/02/2019

**Comment by remihellotomo** [comment]
Purchases can be made within the app as of build 4.1.12. Issue with Apple product rejection meant that we were having the Pick a Plan modal crash in app. This has since been fixed in 4.1.12.  For the time-being, we have removed the trial period from 7 days to 30 days, so no one would be asked to pay (and see the crash).  By June 11th, we should be taking payment (and reinstate the 7 day trial logic).
