### ISSUE TITLE
ORCHA Review Improvements

### ISSUE THREAD

**Issue by eddieTomo** [remihellotomo/Tomo-Office#88]
##  Summary

As Tomo, I want to assess and implement the recommendations from the ORCHA Review so our rating improves in future reviews.

##  Acceptance Criteria

>We couldn’t find a Data Privacy Policy, or Statement, published within the app.

  - [ ] Make privacy policy viewable **in app** in profile modal after onboarding, without needing to load an external browser
  - [ ] Make T&Cs viewable **in app** in profile modal after onboarding, without needing to load an external browser

>We couldn’t find any functionality within the app to allow the user to set their own individual preferred privacy controls. It can be of huge benefit for an App to share its data with other Apps, devices and systems. This should only be done with the express consent of the individual of course and providing this type of functionality is a key mechanism to achieve this.

  - [ ] Consider if we want to add functionality to integrate with Apple Health or other health & fitness trackers

>We couldn’t find any confirmation that 'only' data exported by the end user themselves, with their consent to share, would be shared outside of the App

  - [ ] Add **explicit** wording to our Privacy Policy about how data is exported & shared outside of the App.

> There doesn’t appear to be any functionality within the app to allow the user to set their preferences for sharing the app data with other users (e.g. Clinician / Carer / Family Member / Forums / Buddies)?

- [ ] Consider how we might add a feature that enables the user to limit or control who can see their data regardless of the apps function and features.

> The policy doesn’t state that all personally identifiable data will be encrypted in transit between the device and any developer host storage.

- [ ] Add **explicit** wording to our Privacy Policy regarding encryption at rest and/or in storage

> The App data does not provide any documented policy, or process, for managing Data confidentiality breaches.

- [ ] Revise and publicly publish our data breach handling policy

> The App does not contain a clearly identified 'HOME' button to aid navigation

- [ ] Add functionality to go straight back to the start up page from any page within the app.

> There is no statement of commitment from the developers on their willingness and commitment to addressing user issues with the App.

- [ ] Add **explicit** wording to our published support policies regarding willingness and commitment to address user issues
- [ ] Add a timeframe commitment for dealing with user issues.

>The policy doesn’t provide any statements regarding compliance with recognised International Data Management Standards (ISO, BSI etc.).
>The policy doesn’t provide any statements regarding compliance with recognised NHS Data Standards (e.g. NHS IG toolkit)

- [ ]  Add **explicit** wording to our policies about how we meet or aim to comply with relevant Data Management Standards
- [ ]  Add **explicit** wording to our policies about how we meet or aim to comply with relevant NHS Data Standards

> It wasn't clear from our review how regularly the advice and guidance given by the App was reviewed and updated by relevant professionals.

- [ ] Consider how we might display this in the App

> The App presents no evidence of compliance with International Design Standards (e.g. W3C, BSI, ISO etc.)

- [ ]  Add **explicit** wording to our policies about how we meet or aim to comply with relevant International Design Standards

> The App provides no evidence that its font type can be customised to suit a user's preference
> The App provides no evidence that its font size can be customised to suit a user's preference
> The App provides no evidence that font colours can be customised to suit a customer’s preference
> The App provides no evidence the App's presentation themes can be customised to suit a user's preference.

- [ ] Add functionality for users to customise readability features in the App

> The App does not contain a clearly identified 'HELP' or 'ABOUT' button to aid navigation

- [ ] Add relevant HELP features with an icon to every screen in the App

> The App does not contain clearly defined 'SEARCH' options to aid information finding.

- [ ] Consider if we want to add as search activities feature to our app (either in Explore, Chatbot, or both) as we continue to add more options.

> App reviewed on iPad

- [ ] Add full screen support for iPad

##  Definition of Done

Acceptance Criteria signed off
All attached issues closed
Tomo App recieves a higher score in a future ORCHA review
Tomo App recieves less recommendations in a future ORCHA Review

**Comment by eddieTomo** [comment]
Added as a single Epic issue for now with ORCHA recommendations and suggested actions for us to take listed in the Acceptance Criteria.

**Comment by eddieTomo** [comment]
Recommendations under this issue have largely been created as tickets in the main tomo board, and the Acceptance Criteria is now updated as we have since updated our App and Policies significantly.  I will close this issue for now and create a new one if additional issues remain in our next review
